<a href="https://colab.research.google.com/github/Ayesha-Zaman/Intelligence-Journey-/blob/main/06%3A%20Pandas/%20Pandas%20Series/%20Topic%2016%3A%20Pandas%20Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is Pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

https://pandas.pydata.org/about/index.html

### Pandas Series

A Pandas Series is like a column in a table. It is a 1-D array holding data of any type.

### Importing Pandas

In [106]:
import numpy as np
import pandas as pd

In [107]:
# like python, pandas also have many objects. The two major or prominent are:
# Series
# DataFrame

### Series from lists

In [108]:
# string
countries = ['Pakistan','Bangladesh','America', 'India', 'China']
pd.Series(countries)

0      Pakistan
1    Bangladesh
2       America
3         India
4         China
dtype: object

In [109]:
# In pandas 99% of the time "dtype: object" refers to string datatype

In [110]:
# Integers
runs = [31,45,67,27,100]
run_ser = pd.Series(runs)
run_ser

0     31
1     45
2     67
3     27
4    100
dtype: int64

In [111]:
# custom index
marks = [67,57,89,100]
subjects = ['maths','english','science','Quranic_std']

pd.Series(marks, index=subjects)

maths           67
english         57
science         89
Quranic_std    100
dtype: int64

In [112]:
# setting a name
marks = pd.Series(marks, index=subjects, name="Ayesha's school marks")
marks

maths           67
english         57
science         89
Quranic_std    100
Name: Ayesha's school marks, dtype: int64

### Series from dict

In [113]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'Quranic_std':100
}

marks_series = pd.Series(marks, name="Ayesha's school marks")
marks_series

maths           67
english         57
science         89
Quranic_std    100
Name: Ayesha's school marks, dtype: int64

In [114]:
# size      ->no. of items
marks_series.size

4

In [115]:
# dtype
marks_series.dtype

dtype('int64')

In [116]:
# name
marks_series.name

"Ayesha's school marks"

In [117]:
# is_unique   ->are all items unique?
marks_series.is_unique

True

In [118]:
pd.Series([1,1,2,3,4,3,5]).is_unique

False

In [119]:
# index
marks_series.index

Index(['maths', 'english', 'science', 'Quranic_std'], dtype='object')

In [120]:
run_ser.index

RangeIndex(start=0, stop=5, step=1)

In [121]:
# value
marks_series.values

array([ 67,  57,  89, 100])

### Series using read_csv

In [139]:
# with one col
subs = pd.read_csv('/content/subs.csv').squeeze(True)
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [140]:
# with 2 cols
vk_runs = pd.read_csv("/content/kohli_ipl.csv", index_col='match_no').squeeze(True)
vk_runs

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [141]:
movies = pd.read_csv("/content/bollywood.csv", index_col='movie').squeeze(True)
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

### Series methods

In [125]:
# head and tail
# It gives preview of the given data
# by default shows top 5 or bottom 5 rows

In [126]:
# head
subs.head()

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [127]:
# for top10 values
vk_runs.head(10)

match_no
1      1
2     23
3     13
4     12
5      1
6      9
7     34
8      0
9     21
10     3
Name: runs, dtype: int64

In [128]:
# tail

# subs.tail()
subs.tail(10)

355    149
356    156
357    177
358    210
359    209
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, dtype: int64

In [129]:
# sample
# generate random values from the whole data
# used to remove biasness of data
movies.sample()

movie
Bypass Road (film)    Neil Nitin Mukesh
Name: lead, dtype: object

In [130]:
movies.sample(8)

movie
Raaz: The Mystery Continues      Kangana Ranaut
Woodstock Villa                   Sikander Kher
Bajrangi Bhaijaan                   Salman Khan
Yeh Saali Aashiqui                 Vardhan Puri
Nirdosh                            Ashmit Patel
Riyasat (film)                    Rajesh Khanna
Batti Gul Meter Chalu             Shahid Kapoor
De Taali                       Aftab Shivdasani
Name: lead, dtype: object

In [131]:
# value_counts -> movies
# frequency count of a value

movies.value_counts()

lead
Akshay Kumar         48
Amitabh Bachchan     45
Ajay Devgn           38
Salman Khan          31
Sanjay Dutt          26
                     ..
Seema Azmi            1
Akanksha Puri         1
Charanpreet Insan     1
Jaideep Ahlawat       1
Monali Thakur         1
Name: count, Length: 566, dtype: int64

In [132]:
# sort_values -> inplace

In [133]:
# let's suppose finding the highest scores of a player in ipl cricket match

In [134]:
vk_runs.sort_values(ascending=False).head(1).values[0]

np.int64(113)

In [135]:
vk_runs.sort_values(ascending=False)

match_no
128    113
126    109
123    108
120    100
164    100
      ...
93       0
130      0
206      0
207      0
211      0
Name: runs, Length: 215, dtype: int64

In [136]:
# inplace changes the data permanently

In [137]:
# sort_index -> inplace -> movies
movies.sort_index(ascending=False,inplace=True)

In [138]:
movies

movie
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Zokkomon                       Darsheel Safary
Zindagi Tere Naam           Mithun Chakraborty
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi 50-50                      Veena Malik
                                   ...
2 States (2014 film)              Arjun Kapoor
1971 (2007 film)                Manoj Bajpayee
1920: The Evil Returns             Vicky Ahuja
1920: London                     Sharman Joshi
1920 (film)                   Rajniesh Duggall
Name: lead, Length: 1500, dtype: object

### Series Maths Methods

In [142]:
# count
vk_runs.count()

np.int64(215)

In [148]:
# sum -> product
subs.sum()

np.int64(49510)

In [149]:
# mean -> median -> mode -> std -> var
subs.mean()
print(vk_runs.median())
print(movies.mode())
print(subs.std())
print(vk_runs.var())

24.0
0    Akshay Kumar
Name: lead, dtype: object
62.67502303725269
688.0024777222344

In [150]:
# min/max
subs.max()

396

In [151]:
subs.min()

33

In [152]:
# describe
subs.describe()

count    365.000000
mean     135.643836
std       62.675023
min       33.000000
25%       88.000000
50%      123.000000
75%      177.000000
max      396.000000
Name: Subscribers gained, dtype: float64